<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<script type="text/javascript" src="js/js.js"></script>
<link rel="stylesheet" href="css/css.css">
<div>
    <br>
    <div class="text-center">
        <button id="local" type="button" class="btn btn-primary">Update From Cache</button>
    </div>
    <br>
    <div class="text-center">
        <button id="remote" type="button" class="btn btn-primary">Update From Source</button>
    </div>
    <hr>
    <div class="text-center" id="info"></div>
</div>