<? if ($this->rates) : ?>
    <? foreach ($this->rates as $rate) : ?>
        <label class="btn" title="<?= $rate['name'] ?>">
            <input type="checkbox" <?= (in_array($rate['code'], $this->codes) ? 'checked' : '') ?>>
            <?= $rate['code'] ?>
        </label>
    <? endforeach ?>
<? endif; ?>
<hr>
<?= $this->comment ?>
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th>
                Currency
            </th>
            <th>
                Nominal
            </th>            
            <th>
                Name
            </th>
            <th>
                Value
            </th>
        </tr>
    </thead>
    <tbody>
        <? if ($this->rates) : ?>
            <? foreach ($this->rates as $rate) : ?>
                <? if (in_array($rate['code'], $this->codes)) : ?>
                    <tr>
                        <td>
                            <?= $rate['code'] ?>
                        </td>
                        <td>
                            <?= $rate['nominal'] ?>
                        </td>
                        <td>
                            <?= $rate['name'] ?>
                        </td>
                        <td>
                            <?= $rate['value'] ?>
                        </td>
                    </tr>
                <? endif ?>
            <? endforeach ?>
        <? endif; ?>
    </tbody>
</table>